import { ADMIN_PREFIX_PATH } from '@/constants/route.constant'
import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_ITEM,
} from '@/constants/navigation.constant'
import { ADMIN, TEACHER } from '@/constants/roles.constant'
import type { NavigationTree } from '@/@types/navigation'

const adminNavigationConfig: NavigationTree[] = [
    {
        key: 'Adminapps',
        path: '',
        title: '',
        translateKey: '',
        icon: '',
        type: NAV_ITEM_TYPE_TITLE,
        authority: [ADMIN],
        subMenu: [
            {
                key: 'ExamHub.admin.statistics',
                path: `${ADMIN_PREFIX_PATH}/statistics`,
                title: 'Thống kê',
                translateKey: 'Thống kê',
                icon: 'report',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN],
                subMenu: [],
            },
            {
                key: 'ExamHub.admin.student',
                path: `${ADMIN_PREFIX_PATH}/student`,
                title: 'Sinh viên',
                translateKey: 'Sinh viên',
                icon: 'student',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN],
                subMenu: [],
            },
            {
                key: 'ExamHub.admin.teacher',
                path: `${ADMIN_PREFIX_PATH}/teacher`,
                title: 'Giáo viên',
                translateKey: 'Giáo viên',
                icon: 'teacher',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN],
                subMenu: [],
            },
            {
                key: 'ExamHub.admin.department',
                path: `${ADMIN_PREFIX_PATH}/department`,
                title: 'Khoa',
                translateKey: 'Khoa',
                icon: 'department',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN],
                subMenu: [],
            },
            {
                key: 'ExamHub.admin.class',
                path: `${ADMIN_PREFIX_PATH}/class`,
                title: 'Lớp',
                translateKey: 'Lớp',
                icon: 'class',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN],
                subMenu: [],
            },
            {
                key: 'ExamHub.admin.subject',
                path: `${ADMIN_PREFIX_PATH}/subject`,
                title: 'Môn học',
                translateKey: 'Môn học',
                icon: 'subject',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN],
                subMenu: [],
            },
            {
                key: 'ExamHub.admin.question',
                path: `${ADMIN_PREFIX_PATH}/question`,
                title: 'Câu hỏi',
                translateKey: 'Câu hỏi',
                icon: 'question',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN, TEACHER],
                subMenu: [],
            },
            {
                key: 'ExamHub.admin.exam',
                path: `${ADMIN_PREFIX_PATH}/exam`,
                title: 'Bài thi',
                translateKey: 'Bài thi',
                icon: 'book',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN, TEACHER],
                subMenu: [],
            },
            {
                key: 'ExamHub.admin.examination',
                path: `${ADMIN_PREFIX_PATH}/examination`,
                title: 'Kỳ thi',
                translateKey: 'Kỳ thi',
                icon: 'examination',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [ADMIN, TEACHER],
                subMenu: [],
            },
        ],
    },
]

export default adminNavigationConfig
